#!/usr/bin/env bash

if [[ "${DOTFILES}" == "" ]]; then
    echo "DOTFILES is not set. Exiting to stay safe"
    exit 1
fi

# git stuff
echo -e "\nLinking git configuration..."
rm -f ~/.gitconfig
rm -f ~/.gitignore_global

ln -s $DOTFILES/gitconfig ~/.gitconfig
ln -s $DOTFILES/gitignore_global ~/.gitignore_global

# Get OS identifier so we know where to install stuff
OS=$(uname -s)

if [ "$OS" == 'Darwin' ]; then
    SUBLIME_DIR="$HOME/Library/Application Support/Sublime Text 3"
elif [ "$OS" == 'Linux' ]; then
    SUBLIME_DIR="$HOME/.config/sublime-text-3"
else
    echo -e "\nEnvironment ${OS} is not supported"
    # TODO fix this for BSD. It shouldn't crap out. 
    #  Use a -z check on SUBLIME_DIR in the next step
    exit 1
fi

echo -e "\nLinking Sublime Text configuration..."
echo -e "\tSource: $DOTFILES"
echo -e "\tTarget: $SUBLIME_DIR"

mkdir -p "$SUBLIME_DIR/Packages"
rm -rf   "$SUBLIME_DIR/Packages/User"
ln -s    "$DOTFILES/config/sublime-text-3/Packages/User" \
         "$SUBLIME_DIR/Packages/User"

# tmux
echo -e "\nLinking tmux configuration..."
rm -f $HOME/.tmux.conf
ln -s $DOTFILES/tmux.conf $HOME/.tmux.conf

# vim
echo -e "\nLinking vim configuration..."
#rm -r ~/.vim
test -f ~/.vimrc && rm ~/.vimrc

#ln -s $DOTFILES/vim ~/.vim
ln -s $DOTFILES/vimrc ~/.vimrc

# useful information
_tmux_site="https://wiki.archlinux.org/index.php/tmux"
echo -e "\nDone.\nRead ${_tmux_site} for more information on tmux"

