[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter()]
    [string]$DotfilesRoot,

    [Parameter()]
    [switch]$Force,

    [Parameter()]
    [switch]$Shim
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not $DotfilesRoot) {
    $DotfilesRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\\..")).Path
}

$sourceProfile = Join-Path $DotfilesRoot "Microsoft.PowerShell_profile.ps1"
if (-not (Test-Path -LiteralPath $sourceProfile)) {
    throw "Source profile not found: $sourceProfile"
}

$targetProfile = $PROFILE.CurrentUserCurrentHost
$targetDir = Split-Path -Parent $targetProfile
if (-not (Test-Path -LiteralPath $targetDir)) {
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
}

Write-Host "Dotfiles PowerShell profile setup"
Write-Host "Source: $sourceProfile"
Write-Host "Target: $targetProfile"

function Write-ShimProfile([string]$target, [string]$source) {
    $content = @(
        "# Generated by dotfiles: $(Get-Date -Format o)"
        ". `"$source`""
        ""
    ) -join "`r`n"

    Set-Content -LiteralPath $target -Value $content -Encoding utf8
}

if (Test-Path -LiteralPath $targetProfile) {
    if (-not $Force) {
        throw "Target already exists. Re-run with -Force to back it up and replace it: $targetProfile"
    }

    $backup = "$targetProfile.bak.$(Get-Date -Format yyyyMMdd_HHmmss)"
    Copy-Item -LiteralPath $targetProfile -Destination $backup -Force
    Remove-Item -LiteralPath $targetProfile -Force
    Write-Host "Backed up existing profile to: $backup"
}

if ($Shim) {
    if ($PSCmdlet.ShouldProcess($targetProfile, "Write shim profile")) {
        Write-ShimProfile -target $targetProfile -source $sourceProfile
        Write-Host "Wrote shim profile (dot-sources repo profile)."
    }
    exit 0
}

try {
    if ($PSCmdlet.ShouldProcess($targetProfile, "Create symlink")) {
        New-Item -ItemType SymbolicLink -Path $targetProfile -Target $sourceProfile | Out-Null
        Write-Host "Created symlink profile."
    }
}
catch {
    Write-Warning "Symlink failed ($($_.Exception.Message)). Falling back to shim profile."
    if ($PSCmdlet.ShouldProcess($targetProfile, "Write shim profile")) {
        Write-ShimProfile -target $targetProfile -source $sourceProfile
        Write-Host "Wrote shim profile (dot-sources repo profile)."
    }
}

