---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    # keys
    - name: add apt key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add apt key for google chrome
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
    - name: add apt key for sublime text
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
    - name: add apt key for spotify
      apt_key: 
        keyserver: keyserver.ubuntu.com
        id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 
        state: present
      ignore_errors: yes

    # repositories
    - name: add docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: add google chrome apt repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
    - name: add sublime text apt repository
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/dev/
        state: present
    - name: add spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
      ignore_errors: yes
    # update cache
    - name: update cache after addin new repositories
      apt:
        update_cache: yes
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: fix minor locale issue
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"
    - name: update cache if older than one hour
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install base command line tools
      apt:
        name:
          - vim
          - git
          - tree
          - zsh
          - htop
          - screen
          - tmux
          - trash-cli
        state: present
    - name: install graphical user interface
      apt:
        name:
          - xinit
          - virtualbox-guest-dkms
          - virtualbox-guest-x11
          - openbox
          - rxvt-unicode
          - rofi
          - dunst
          - ttf-ubuntu-font-family
          - i3-wm
          - i3blocks
        state: present
    - name: install sexy icons
      apt:
        deb: https://launchpad.net/~noobslab/+archive/ubuntu/icons/+files/ultra-flat-icons_1.3.2~trusty~Noobslab.com_all.deb
    - name: install development tools and dependencies
      apt:
        name:
          - docker-ce
          - openjdk-8-jdk
          - google-chrome-stable
          - libgtk2.0-0
          - sublime-text
          - maven
          - alien
          - gitg
          - meld
          - libaio1
        state: present
    - name: install spotify
      apt:
        name:
          - spotify-client
      ignore_errors: yes
