---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: install command line tools
      pacman:
        - zsh
        - base-devel
        - jq
        - figlet
        - nethack
      state: latest
